### ISSUE TITLE
BTrDB API service crash

### ISSUE THREAD

**Issue by fredantell** [BTrDB/btrdb-server#49] opened 2017-10-19 19:53 UTC
This isn't a fully baked issue yet since I'm having trouble reproducing the behavior, however, I thought I'd log it in case I can refine the information later.

I seem to have been able to take down our BTrDB API service while sending curl requests to our deployed copy of Mr Plotter. While I haven't been able to completely crash it again I did notice the following.

Specifically, I was sending posts to the /csv endpoint while experimenting with different JSON values in the payload to see the effects on the data returned. I noticed that when sending a request for an alignment queryType of "windows" that I could get a non deterministic response from the DB. Sometimes I would get data, sometimes I would get an error message, and sometimes I'd get an error trying to connect.

Here's the JSON payload with the auth token removed:
```
json={"StartTime":1494405229456,"EndTime":1494405345800,"UUIDS":["2e59878a-62f8-57ff-8834-16de04a45d62"],"Labels":["NavyYard/ pmu3003151/ L1MAG"],"QueryType":"windows","WindowText":"3","WindowUnit":"seconds","UnitofTime":"ms","PointWidth":44,"_token":""}
```
The primary thing that seemed to cause it to fail was changing the PointWidth value, but I'm not sure if I'm simply seeing patterns in randomness.

Here is the curl command I was sending (with auth token stripped again):
```
curl --request POST \
  --url https://viz.predictivegrid.com/csv \
  --header 'accept: text/csv' \
  --header 'accept-encoding: gzip, deflate, br' \
  --header 'accept-language: en-US,en;q=0.8' \
  --header 'cache-control: no-cache' \
  --header 'content-type: text/plain' \
  --header 'dnt: 1' \
  --header 'origin: https://viz.predictivegrid.com' \
  --header 'postman-token: 32b4c31a-fe7c-156c-2d40-cea40fa1b1e3' \
  --header 'referer: https://viz.predictivegrid.com/' \
  --header 'upgrade-insecure-requests: 1' \
  --header 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36' \
  --data 'json={"StartTime":1494405229456,"EndTime":1494405345800,"UUIDS":["2e59878a-62f8-57ff-8834-16de04a45d62"],"Labels":["NavyYard/ pmu3003151/ L1MAG"],"QueryType":"windows","WindowText":"3","WindowUnit":"seconds","UnitofTime":"ms","PointWidth":44,"_token":""}'
```

That either resulted in data being returned, or this error message:
```
Could not complete CSV query: rpc error: code = Internal desc = transport is closing
```
Or it flat out refused to connect.

As I said I haven't been able to reproduce a full crash, but when I did all the API requests stopped responding (e.g. I noticed I could no longer query for streams) although Jerry (@pingthings) relayed that he didn't see anything unusual in the logs.

I'll update this if I figure out more.

**Comment by immesys** [comment] 2017-10-19 20:04
What version of BTrDB are you using?

**Comment by pingthings** [comment] 2017-10-19 20:14
Fred is working on our original install at this point.  So pre 4.6.  I'm building a new cluster to migrate things over to with the latest version.  We're expanding the cluster significantly and reorganizing some things.

**Comment by pingthings** [comment] 2017-11-16 13:01
This has happened again and it a show stopper as we start to pound on the API.   Can we get a graceful throttle or something so that we avoid a complete lock out as a stop gap measure?  Obviously this goes away if we can scale out BTrDB across the cluster though we'd still need throttles and health checks for self-healing of a bad pod who's API is non-responsive.

**Comment by immesys** [comment] 2017-11-16 13:23
BTrdb has throttles, so this is a bug rather than overload. Can you make a reproducing test case?

**Comment by pingthings** [comment] 2017-11-16 13:25
I will get Fred to write something up based on what he's been doing. @fredantell

**Comment by pingthings** [comment] 2017-11-16 14:28
Can we talk about throttles and what these should look like, rules of thumb etc?   Significant impacts too low, too high.  unbalanced pairs? 

resource              pool   queue
----------------------------------
ceph_cold             100    100
ceph_hot               100    100
concurrent_op      500    250
max_conns            250    250
open_read_trees   500    500
open_trees            1000  1000

**Comment by immesys** [comment] 2017-11-18 19:08
The pool is how many of that resource can be "active" at a time, and the queue is how many can be silently blocked waiting for a slot to appear in the pool. After the queue is full, requests immediately get an error along the lines of "cluster is shedding load". Say for example you try to read 600 streams concurrently with the config you posted (but from a single connection). That requires 600 concurrent ops and 600 open_read_trees. The first 500 operations will begin immediately, but the next 100 will silently return no data until some of the first 500 have completed. 

This does have some nuances. Imagine the consumer is reading one point from every stream before progressing, it would actually deadlock because the earlier 500 ops won't progress unless the client consumes the data on its side.

We can discuss this in more detail, but the throttles would make the API "hang" not say "transport is closing", and it should not be hit under normal circumstances, so there might be something else afoot. Let me know when you have the reproducer and I will do some testing

**Comment by immesys** [comment] 2017-11-18 19:08
Ping @pingthings and @fredantell, not sure if you will see notification given that I moved the repo

**Comment by fredantell** [comment] 2018-01-01 19:47
I tried this weekend to reproduce some of the crashes that we've seen. We've noticed the API hanging in two situations. 

* From some of the malformed requests that I detailed above
* From an attempt I made to put the Mr Plotter go webserver under heavy load

Now I can't reproduce either of these. I did my best to follow the steps I outlined above as well as anything I could remember from my original issue and was not able to take down either our https://viz.predictivegrid.com or a local dev cluster created with your smartgridstore devmachine tools, Michael.

Previously a couple quick bursts of 500 requests each to the Mr Plotter go webserver was enough to hang the API front end (MRP's go server kept responding, but requests that required forwarding onto BTrDB appeared to be loading indefinitely). I was able to send roughly 20,000 requests to both my local dev cluster as well as viz.predictivegrid.com this time around and everything was handled properly and I verified all the responses contained the correct data. I tried it on different accounts with access to different streams as well in the off case it had to do less with the volume and perhaps more with an issue idiosyncratic to some individual stream or data. That however made no difference either.

If in the course of our work we're able to take it down again then we'll pay close attention to what was going on. If you have anything you'd like us to test, I'm also more than happy to try again.

**Comment by murphsp1** [comment] 2018-01-02 13:34
At least part of this problem arises from a divide by zero bug making a "window" request with the width parameter set to 0 (ns). This causes a repeatable BTrDB crash:

btrdb-0 btrdb panic: runtime error: integer divide by zero

From the Python API, you see:

```python
_Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Endpoint read failed)>
```

**Comment by fredantell** [comment] 2018-01-02 15:28
I replicated this using a local cluster as well and was able to get the same error message as my original post: (returned when querying for csv data from the Mr Plotter go server)
`Could not complete CSV query: rpc error: code = Internal desc = transport is closing`

Looks like we still have an entirely separate issue that I observed with the API hanging when fed a large amount of queries (that I failed entirely to replicate the other day), but this looks exactly like the originally reported issue.

**Comment by pingthings** [comment] 2018-01-02 15:46
Following is a log of the even post panic.

[error-log-BTRDB-crash.txt](https://github.com/BTrDB/btrdb-server/files/1597954/error-log-BTRDB-crash.txt)

**Comment by pingthings** [comment] 2018-01-02 15:50
Also,   BTrDB exhibited a behavior in the logs that I had not previously seen.  The following is post crash restart of BTrDB.  The following are fragments of the logs and this type of logging went on for approximately 5 minutes.  Some clarification of what these types of logs indicate would be beneficial for documentation sake.
'btrdb-0 btrdb [WARNING]qtree.go:1089 > Fragmentation needed depth=10 active=true a=0xc4291e6c60
btrdb-0 btrdb [WARNING]qtree.go:1091 > no hole
btrdb-0 btrdb [WARNING]qtree.go:1093 > Depth ok
btrdb-0 btrdb [WARNING]qtree.go:1089 > Fragmentation needed depth=10 active=true a=0xc4291e6c60
btrdb-0 btrdb [WARNING]qtree.go:1091 > no hole
btrdb-0 btrdb [WARNING]qtree.go:1093 > Depth ok
btrdb-0 btrdb [WARNING]qtree.go:1164 > leaf
btrdb-0 btrdb [WARNING]qtree.go:1089 > Fragmentation needed depth=10 active=true a=0xc4291e6c60
btrdb-0 btrdb [WARNING]qtree.go:1091 > no hole'

Which were generally followed by these entries
`btrdb-0 btrdb [WARNING]qtree.go:1146 > emitting in hole loop nxtstart=1495145760021035000
btrdb-0 btrdb [WARNING]qtree.go:1146 > emitting in hole loop nxtstart=1495145760021036000
btrdb-0 btrdb [WARNING]qtree.go:1146 > emitting in hole loop nxtstart=1495145760021037000
btrdb-0 btrdb [WARNING]qtree.go:1146 > emitting in hole loop nxtstart=1495145760021038000
btrdb-0 btrdb [WARNING]qtree.go:1146 > emitting in hole loop nxtstart=1495145760021039000
btrdb-0 btrdb [WARNING]qtree.go:1146 > emitting in hole loop nxtstart=1495145760021040000
btrdb-0 btrdb [WARNING]qtree.go:1146 > emitting in hole loop nxtstart=1495145760021041000
btrdb-0 btrdb [WARNING]qtree.go:1146 > emitting in hole loop nxtstart=1495145760021042000
^Cbtrdb-0 btrdb [WARNING]qtree.go:1146 > emitting in hole loop nxtstart=1495145760021043000
btrdb-0 btrdb [WARNING]qtree.go:1146 > emitting in hole loop nxtstart=1495145760021044000`

**Comment by immesys** [comment] 2018-01-02 15:57
Those are emitted by the window code, but Mr Plotter uses alignedwindows

**Comment by immesys** [comment] 2018-01-02 15:59
It's there because I got a bug report that the generated windows are sometimes incorrect (in their time intervals) when there are holes in the data but i couldn't reproduce, so keeping those logs to debug in case it shows up again

**Comment by immesys** [comment] 2018-01-02 16:00
I'll remove them in the next version, they will slow things down in production.

**Comment by immesys** [comment] 2019-02-10 18:35
This was fixed a while ago

**Closed by immesys** 2019-02-10 18:35 UTC
